apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fum2cs6et-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fum2cs6et-python 
  name: fum2cs6et-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fum2cs6et-python 
